### ISSUE TITLE
sort order?

### ISSUE THREAD

**Issue by cmnord** [techx/hackmit-code#5]
as we get more projects, maybe we should consider how to sort/categorize. suggested order by @nmoroze:

- dayof (quill, helpq, gavel, cog)
- internal (offix, redisred, hubot things)
- external (splash, puzzle)

**Comment by nmoroze** [comment]
I was thinking of adding these sections w/ a little nav at the top to jump to each one

**Comment by anishathalye** [comment]
When I wrote the original version, the idea was to have the most interesting / innovative ones first. That way, the above-the-fold content looks really interesting to someone who lands on the page.
